# Generated by IBM TransformationAdvisor
# Mon May 17 07:56:42 UTC 2021

FROM ibmcom/websphere-traditional:latest-ubi

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --chown=was:root db2app-1.war /work/config/db2app-1.war
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/config/lib
RUN /work/configure.sh
